return {
  -- "jackMort/ChatGPT.nvim",
  -- event = "VeryLazy",
  -- config = function()
  --   function get_key()
  --     local file = io.popen("cat ~/.chatgpt/secret.txt")
  --     local key = file:read("*a")
  --     file:close()
  --
  --     return "echo " .. key
  --   end
  --
  --   local chatgpt = require("chatgpt")
  --
  --   chatgpt.setup({
  --     api_key_cmd = get_key(),
  --     yank_register = "+",
  --     edit_with_instructions = {
  --       diff = false,
  --       keymaps = {
  --         close = "<C-c>",
  --         accept = "<C-y>",
  --         toggle_diff = "<C-d>",
  --         toggle_settings = "<C-o>",
  --         toggle_help = "<C-h>",
  --         cycle_windows = "<Tab>",
  --         use_output_as_input = "<C-i>",
  --       },
  --     },
  --     chat = {
  --       open_extra_panels = {
  --         help_panel = true
  --       },
  --       welcome_message = "Hello, striker!!",
  --       loading_text = "Loading, please wait ...",
  --       question_sign = "",
  --       answer_sign = "ﮧ",
  --       max_line_length = 120,
  --       sessions_window = {
  --         border = {
  --           style = "rounded",
  --           text = {
  --             top = " Sessions ",
  --           },
  --         },
  --         win_options = {
  --           winhighlight = "Normal:Normal,FloatBorder:FloatBorder",
  --         },
  --       },
  --       keymaps = {
  --         close = { "<C-c>" },
  --         yank_last = "<C-k>",
  --         yank_last_code = "<C-y>",
  --         scroll_up = "<C-u>",
  --         scroll_down = "<C-d>",
  --         new_session = "<C-n>",
  --         toggle_help = "<C-h>",
  --         cycle_windows = "<tab>",
  --         cycle_modes = "<C-f>",
  --         select_session = "<Space>",
  --         rename_session = "r",
  --         delete_session = "d",
  --         draft_message = "<C-d>",
  --         toggle_settings = "<C-o>",
  --         toggle_message_role = "<C-r>",
  --         toggle_system_role_open = "<C-s>",
  --       },
  --     },
  --     popup_layout = {
  --       default = "center",
  --       center = {
  --         width = "80%",
  --         height = "80%",
  --       },
  --       right = {
  --         width = "30%",
  --         width_settings_open = "50%",
  --       },
  --     },
  --     popup_window = {
  --       border = {
  --         highlight = "FloatBorder",
  --         style = "rounded",
  --         text = {
  --           top = " ChatGPT ",
  --         },
  --       },
  --       win_options = {
  --         wrap = true,
  --         linebreak = true,
  --         foldcolumn = "1",
  --         winhighlight = "Normal:Normal,FloatBorder:FloatBorder",
  --       },
  --       buf_options = {
  --         filetype = "markdown",
  --       },
  --     },
  --     system_window = {
  --       border = {
  --         highlight = "FloatBorder",
  --         style = "rounded",
  --         text = {
  --           top = " SYSTEM ",
  --         },
  --       },
  --       win_options = {
  --         wrap = true,
  --         linebreak = true,
  --         foldcolumn = "2",
  --         winhighlight = "Normal:Normal,FloatBorder:FloatBorder",
  --       },
  --     },
  --     popup_input = {
  --       prompt = "  ",
  --       border = {
  --         highlight = "FloatBorder",
  --         style = "rounded",
  --         text = {
  --           top_align = "center",
  --           top = " Prompt ",
  --         },
  --       },
  --       win_options = {
  --         winhighlight = "Normal:Normal,FloatBorder:FloatBorder",
  --       },
  --       submit = "<C-Enter>",
  --       submit_n = "<Enter>",
  --     },
  --     settings_window = {
  --       border = {
  --         style = "rounded",
  --         text = {
  --           top = " Settings ",
  --         },
  --       },
  --       win_options = {
  --         winhighlight = "Normal:Normal,FloatBorder:FloatBorder",
  --       },
  --     },
  --     openai_params = {
  --       model = "gpt-4o-mini",
  --       frequency_penalty = 0,
  --       presence_penalty = 0,
  --       max_tokens = 16000,
  --       temperature = 0.2,
  --       top_p = 0.5,
  --       n = 1,
  --     },openai_edit_params = {
  --       model = "gpt-4o-mini",
  --       frequency_penalty = 0,
  --       presence_penalty = 0,
  --       max_tokens = 16000,
  --       temperature = 0.2,
  --       top_p = 0.5,
  --       n = 1,
  --     },
  --     actions_paths = {},
  --     show_quickfixes_cmd = "Trouble quickfix",
  --     predefined_chat_gpt_prompts = "https://raw.githubusercontent.com/f/awesome-chatgpt-prompts/main/prompts.csv",
  --   })
  --
  --   vim.api.nvim_set_keymap('n', '<Leader>gc', ':ChatGPT<cr>', { noremap = true, silent = true })
  --   vim.api.nvim_set_keymap('n', '<Leader>gi', ':ChatGPTEditWithInstructions<cr>', { noremap = true, silent = true })
  --   vim.api.nvim_set_keymap('v', '<Leader>gi', ':ChatGPTEditWithInstructions<cr>', { noremap = true, silent = true })
  --   vim.api.nvim_set_keymap('n', '<Leader>ga', ':ChatGPTActAs<cr>', { noremap = true, silent = true })
  -- end,
  -- dependencies = {
  --   "MunifTanjim/nui.nvim",
  --   "nvim-lua/plenary.nvim",
  --   "nvim-telescope/telescope.nvim"
  -- }
}
