-- return {
-- 	"holdmypotion/loona",
-- 	dependencies = {
-- 		"nvim-lua/plenary.nvim", -- Required for some utility functions
-- 	},
-- 	config = function()
-- 		require("gemini-chat").setup({
-- 			-- Your configuration here
-- 		})
-- 	end,
-- }
return {
-- 	dir = vim.fn.expand("~/personal/neovim/loona"), -- Adjust path
-- 	name = "gemini-chat.nvim",
-- 	dev = true,
--
-- 	dependencies = {
-- 		"nvim-lua/plenary.nvim",
-- 	},
--
-- 	config = function()
-- 		require("gemini-chat").setup({
-- 			-- Your configuration here
-- 		})
-- 	end,
}
