return {
	-- {
	--     "iamcco/markdown-preview.nvim",
	--     cmd = { "MarkdownPreviewToggle", "MarkdownPreview", "MarkdownPreviewStop" },
	--     build = "cd app && yarn install",
	--     init = function()
	--         vim.g.mkdp_filetypes = { "markdown" }
	--     end,
	--     ft = { "markdown" },
	-- },
	-- {
	--     "epwalsh/obsidian.nvim",
	--     version = "*", -- recommended, use latest release instead of latest commit
	--     lazy = true,
	--     ft = "markdown",
	--     -- Replace the above line with this if you only want to load obsidian.nvim for markdown files in your vault:
	--     event = {
	--       -- If you want to use the home shortcut '~' here you need to call 'vim.fn.expand'.
	--       -- E.g. "BufReadPre " .. vim.fn.expand "~" .. "/my-vault/**.md"
	--       "BufReadPre path/to/my-vault/**.md",
	--       "BufNewFile path/to/my-vault/**.md",
	--     },
	--     dependencies = {
	--         "nvim-lua/plenary.nvim",
	--     },
	--     config = function()
	--         require("obsidian").setup({
	--             follow_url_func = function(url)
	--                 vim.fn.jobstart({ "open", url }) -- Mac OS
	--             end,
	--             follow_img_func = function(img)
	--                 vim.fn.jobstart { "qlmanage", "-p", img } -- Mac OS quick look preview
	--             end,
	--             workspaces = {
	--                 {
	--                     name = "White_Room",
	--                     path = "~/White_room/vault",
	--                 },
	--                 {
	--                     name = "no-vault",
	--                     path = function()
	--                         -- alternatively use the CWD:
	--                         -- return assert(vim.fn.getcwd())
	--                         return assert(vim.fs.dirname(vim.api.nvim_buf_get_name(0)))
	--                     end,
	--                     overrides = {
	--                         notes_subdir = vim.NIL, -- have to use 'vim.NIL' instead of 'nil'
	--                         new_notes_location = "current_dir",
	--                         templates = {
	--                             folder = vim.NIL,
	--                         },
	--                         disable_frontmatter = true,
	--                     },
	--                 },
	--             },
	--             templates = {
	--                 folder = "templates",
	--                 date_format = "%d-%m-%Y",
	--                 substitutions = {
	--                     ['date:YYYYMMDD'] = function()
	--                         return os.date("%Y%m%d")
	--                     end,
	--                     ['time:HHmm'] = function()
	--                         return os.date("%H%M")
	--                     end
	--                 }
	--             },
	--             disable_frontmatter = true
	--         })
	--         vim.opt.conceallevel = 2
	--
	--         vim.keymap.set("n", "gf", function()
	--             if require("obsidian").util.cursor_on_markdown_link() then
	--                 return "<cmd>ObsidianFollowLink<CR>"
	--             else
	--                 return "gf"
	--             end
	--         end, { noremap = false, expr = true })
	--
	--         vim.keymap.set('n', '<leader>ot', '<CMD>ObsidianTemplate<CR>', { desc = '[O]bsidian [T]emplates' })
	--     end
	-- }
}
