-- Themes
--
return {
  -- "thedenisnikulin/vim-cyberpunk",
  -- config = function()
  --   vim.cmd.colorscheme("silverhand")
  --   vim.g.airline_theme = "silverhand"
  --   vim.opt.termguicolors = true
  --   vim.opt.cursorline = true
  --   vim.api.nvim_set_hl(0, "CursorLine", { bg = "black" })
  --   vim.g.airline_theme = "silverhand"
  -- end,
}
--

-- return {
--   "catppuccin/nvim",
--   name = "catppuccin",
--   priority = 1000,
--   config = function()
--     vim.cmd.colorscheme "catppuccin"
--   end,
-- }
-- return {
--   -- "Shatur/neovim-ayu",
--   --
--   -- config = function()
--   --   require("ayu").setup({
--   --     mirage = true,
--   --   })
--   --   vim.cmd.colorscheme("ayu")
--   -- end,
--   "oxfist/night-owl.nvim",
--   lazy = false, -- make sure we load this during startup if it is your main colorscheme
--   priority = 1000, -- make sure to load this before all the other start plugins
--   config = function()
--     -- load the colorscheme here
--     require("night-owl").setup()
--     vim.cmd.colorscheme("night-owl")
--   end,
-- }
