return {
  "folke/trouble.nvim",
  dependencies = {
    "nvim-tree/nvim-web-devicons",
  },
  cmd = { "TroubleToggle", "Trouble" },
  opts = {
    position = "bottom",
    height = 10,
    width = 50,
    icons = true,
    mode = "document_diagnostics",
    severity = nil,
    fold_open = "",
    fold_closed = "",
    group = true,
    padding = true,
    auto_close = true,
    auto_preview = true,
    auto_fold = true,
    signs = {
      error = "",
      warning = "",
      hint = "",
      information = "",
      other = "",
    },
    use_diagnostic_signs = true,
    action_keys = {
      close = {"q", "<esc>"},
      cancel = "<c-e>",
      refresh = "r",
      jump = {"<cr>", "<tab>"},
      toggle_mode = "m",
      toggle_preview = "P",
      preview = "p",
      close_folds = {"zM", "zm"},
      open_folds = {"zR", "zr"},
      toggle_fold = {"zA", "za"},
      previous = "k",
      next = "j",
    },
  },
  keys = {
    { "<leader>xx", function() require("trouble").toggle("document_diagnostics") end, desc = "Document Diagnostics (Trouble)" },
    { "<leader>xX", function() require("trouble").toggle("workspace_diagnostics") end, desc = "Workspace Diagnostics (Trouble)" },
    { "<leader>xL", function() require("trouble").toggle("loclist") end, desc = "Location List (Trouble)" },
    { "<leader>xQ", function() require("trouble").toggle("quickfix") end, desc = "Quickfix List (Trouble)" },
  },
}
